version: "2"
services:
  api:
    # restart: on-failure
    container_name: app
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./:/home/node/api/
    environment:
      - MONGO_URL=mongodb://root:potato@mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: .
    ports:
      - 8000:8000
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongodb:
    # restart: on-failure
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=potato
    command: mongod --auth
    volumes:
      - mongodb:/data/db/
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    # restart: on-failure
    image: redis:latest
    networks:
      - backend
    volumes:
      - redis:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - api
  #   networks:
  #     - backend
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100MB"
  #       max-file: "3"

networks:
  backend:

volumes:
  mongodb:
  redis:
